import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="container min-h-[83vh] p-2 mx-auto">{children}</div>
      </body>
    </html>
  );
}
